package com.example.taskdemo.scheduler;

import com.example.taskdemo.dto.TaskCreationDto;
import com.example.taskdemo.service.TaskService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;

@Component
public class TaskCreationScheduler {

    @Autowired
    TaskService taskService;

    private static final Logger log = LoggerFactory.getLogger(TaskCreationScheduler.class);

    @Scheduled(fixedRate = 900000)
    public void createNewTask() {
        TaskCreationDto newTask = new TaskCreationDto();
        newTask.setTitle("New Task");
        newTask.setDescription("Autogenerated Task");
        newTask.setDueDate(LocalDate.now().plusDays(1));
        taskService.createTask(newTask);
        log.info("Scheduled new Task: " + newTask.getTitle());
    }
}
